urdf: shadow_hand.urdf
link_radius: 0.05
base_links:
  - world
  - world
  - world
  - world
  - world
ee_links:
  - rh_fftip
  - rh_mftip
  - rh_rftip
  - rh_lftip
  - rh_thtip
joint_ordering: ['rh_WRJ2', 'rh_WRJ1', 'rh_FFJ4', 'rh_FFJ3', 'rh_FFJ2', 'rh_FFJ1', 'rh_MFJ4', 'rh_MFJ3', 'rh_MFJ2', 'rh_MFJ1', 'rh_RFJ4', 'rh_RFJ3', 'rh_RFJ2', 'rh_RFJ1', 'rh_LFJ5', 'rh_LFJ4', 'rh_LFJ3', 'rh_LFJ2', 'rh_LFJ1', 'rh_THJ5', 'rh_THJ4', 'rh_THJ3', 'rh_THJ2', 'rh_THJ1']
starting_config: [-0.2163, -0.0909, -0.2168, 0.5369, 0.9744, 0.7873, -0.1805, 0.5807, 0.8614, 0.7873, 0.1843, 0.5342, 0.9090, 0.7873, 0.2396, -0.2271, 0.8539, 0.2979, 0.7873, -0.3318, 0.6962, -0.1297, 0.0616, 0.6560]
obstacles: