urdf: shadow_hand.urdf
link_radius: 0.05
base_links:
  - world
  - world
  - world
  - world
  - world
ee_links:
  - rh_fftip
  - rh_mftip
  - rh_rftip
  - rh_lftip
  - rh_thtip
joint_ordering: ['rh_WRJ2', 'rh_WRJ1', 'rh_FFJ4', 'rh_FFJ3', 'rh_FFJ2', 'rh_FFJ1', 'rh_MFJ4', 'rh_MFJ3', 'rh_MFJ2', 'rh_MFJ1', 'rh_RFJ4', 'rh_RFJ3', 'rh_RFJ2', 'rh_RFJ1', 'rh_LFJ5', 'rh_LFJ4', 'rh_LFJ3', 'rh_LFJ2', 'rh_LFJ1', 'rh_THJ5', 'rh_THJ4', 'rh_THJ3', 'rh_THJ2', 'rh_THJ1']
starting_config: [-0.2340, -0.0626, -0.2651, 0.3715, 0.9776, 0.7896, -0.2439, 0.5323, 0.7328, 0.7896, 0.0236, 0.4212, 0.7399, 0.7896, 0.2034, -0.2559, 0.8240, 0.3861, 0.7896, -0.4124, 0.8688, -0.1460, 0.5413, 0.6579]
obstacles: