urdf: myohand_kinematics_two_hands_scaled.urdf
link_radius: 0.05
base_links:
  - world
  - world
  - world
  - world
  - world
  - world
  - world
  - world
  - world
  - world
ee_links:
  - THtip
  - IFtip
  - MFtip
  - RFtip
  - LFtip
  - THtip_left
  - IFtip_left
  - MFtip_left
  - RFtip_left
  - LFtip_left
joint_ordering: ['translate_x_joint', 'translate_y_joint', 'translate_z_joint', 'rotate_x_joint', 'rotate_y_joint', 'rotate_z_joint', 'cmc_abduction', 'cmc_flexion', 'mp_flexion', 'ip_flexion', 'mcp2_flexion', 'mcp2_abduction', 'pm2_flexion', 'md2_flexion', 'mcp3_flexion', 'mcp3_abduction', 'pm3_flexion', 'md3_flexion', 'mcp4_flexion', 'mcp4_abduction', 'pm4_flexion', 'md4_flexion', 'mcp5_flexion', 'mcp5_abduction', 'pm5_flexion', 'md5_flexion', 'translate_x_joint_left', 'translate_y_joint_left', 'translate_z_joint_left', 'rotate_x_joint_left', 'rotate_y_joint_left', 'rotate_z_joint_left', 'cmc_abduction_left', 'cmc_flexion_left', 'mp_flexion_left', 'ip_flexion_left', 'mcp2_flexion_left', 'mcp2_abduction_left', 'pm2_flexion_left', 'md2_flexion_left', 'mcp3_flexion_left', 'mcp3_abduction_left', 'pm3_flexion_left', 'md3_flexion_left', 'mcp4_flexion_left', 'mcp4_abduction_left', 'pm4_flexion_left', 'md4_flexion_left', 'mcp5_flexion_left', 'mcp5_abduction_left', 'pm5_flexion_left', 'md5_flexion_left']
starting_config: [0.2609, 0.6242, 0.0651, -0.1664, -0.2719, -1.6329, 0.1498, -0.4662, -0.1151, -0.8304, 0.403, -0.1012, 0.280, 0.138, 0.4269, -0.191, 0.3847, 0.1828, 0.2085, -0.25, 0.2281, 0.1134, 0.0527, -0.2618, 0.0505, 0.0267, 0.2794, 0.4342, 0.0511, 0.1151, -0.1178, -1.6942, 0.0357, -0.5525, -0.3386, -1.0815, 0.536, -0.172, 0.3516, 0.1592, 0.3137, -0.2441, 0.291, 0.1399, 0.2304, -0.2618, 0.2326, 0.1083, 0.0, -0.2618, 0.0, 0.0]
obstacles: