urdf: myohand_kinematics_two_hands_scaled.urdf
link_radius: 0.05
base_links:
  - world
  - world
  - world
  - world
  - world
  - world
  - world
  - world
  - world
  - world
ee_links:
  - THtip
  - IFtip
  - MFtip
  - RFtip
  - LFtip
  - THtip_left
  - IFtip_left
  - MFtip_left
  - RFtip_left
  - LFtip_left
joint_ordering: ['translate_x_joint', 'translate_y_joint', 'translate_z_joint', 'rotate_x_joint', 'rotate_y_joint', 'rotate_z_joint', 'cmc_abduction', 'cmc_flexion', 'mp_flexion', 'ip_flexion', 'mcp2_flexion', 'mcp2_abduction', 'pm2_flexion', 'md2_flexion', 'mcp3_flexion', 'mcp3_abduction', 'pm3_flexion', 'md3_flexion', 'mcp4_flexion', 'mcp4_abduction', 'pm4_flexion', 'md4_flexion', 'mcp5_flexion', 'mcp5_abduction', 'pm5_flexion', 'md5_flexion', 'translate_x_joint_left', 'translate_y_joint_left', 'translate_z_joint_left', 'rotate_x_joint_left', 'rotate_y_joint_left', 'rotate_z_joint_left', 'cmc_abduction_left', 'cmc_flexion_left', 'mp_flexion_left', 'ip_flexion_left', 'mcp2_flexion_left', 'mcp2_abduction_left', 'pm2_flexion_left', 'md2_flexion_left', 'mcp3_flexion_left', 'mcp3_abduction_left', 'pm3_flexion_left', 'md3_flexion_left', 'mcp4_flexion_left', 'mcp4_abduction_left', 'pm4_flexion_left', 'md4_flexion_left', 'mcp5_flexion_left', 'mcp5_abduction_left', 'pm5_flexion_left', 'md5_flexion_left']
starting_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5, -0.78, -0.785398, -1.309, 0.0, -0.261799, 0.0, 0.0, 0.0, -0.261799, 0.0, 0.0, 0.0, -0.261799, 0.0, 0.0, 0.0, -0.261799, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.5, -0.78, -0.785398, -1.309, 0.0, -0.261799, 0.0, 0.0, 0.0, -0.261799, 0.0, 0.0, 0.0, -0.261799, 0.0, 0.0, 0.0, -0.261799, 0.0, 0.0]
obstacles: