urdf: leap.urdf
link_radius: 0.05
base_links:
  - palm_lower
  - palm_lower
  - palm_lower
  - palm_lower
ee_links:
  - realtip
  - realtip_2
  - realtip_3
  - realtip_4
joint_ordering: ['1', '0', '2', '3', '5', '4', '6', '7', '9', '8', '10', '11', '12', '13', '14', '15']
starting_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
obstacles: